---
title: Ny blogg med hjälp av R och Blogdown
author: Richard Öhrvall
date: '2017-08-22'
slug: ny-blogg
categories: []
tags:
  - R
  - Blogdown
---
Jag startade min blogg på webbsidan https://richardohrvall.com/ år 2010. Bloggen skapades med hjälp av Wordpress. På många sätt är Wordpress ett utmärkt verktyg för den som vill blogga, men av ett antal skäl har jag på senare tid känt att jag vill byta till ett nytt sätt att blogga. Ett skäl är att jag inte är så förtjust i att först logga in i Wordpress för att sedan kunna börja skriva. Visst, det finns sätt att komma runt detta, men åtminstone de sätt jag själv har testat har varit förhållandevis krångliga. Ett annat skäl är att jag vill kunna integrera analys av data och mitt övriga skrivande med bloggandet på ett bättre sätt. 

Samtidigt har jag för avsikt att successivt gå över till att använda statistikprogrammet R i allt högre grad, och därmed använda Stata i lägre grad. Det finns en rad fördelar med att använda R, och jag kommer säkert att få anledning att återkomma till dessa, men en styrka med programmet är den integration av R-kod och text i Markdown-format som möjliggörs genom [RMarkdown](http://rmarkdown.rstudio.com/index.html) när man använder R i kombination med RStudio. Markdown är ett format för att skriva text utan att fokusera för mycket på formatering andra tekniska aspekter. Texten kan sedan enkelt konverteras till html, pdf eller Word. Enkelt uttryckt är det enkelt och flexibelt och resultatet blir snyggt. RMarkdown gör att man även kan lägga in kod i statistikprogrammet R i dokumentet, antingen för att visa koden eller för att visa resultatet av koden, till exempel i form av en graf eller en tabell. På så vis kan skriva en artikel eller en rapport som kan plockas ut i olika format. Dessutom är allt reproducerbart, vilket gör det enkelt att uppdatera dokumentet om det underliggande datamaterialet uppdateras.   

Det går även skriva en hel bok i Rmarkdown genom R-paketet [Bookdown](https://bookdown.org/yihui/bookdown/). Och nu har upphovsmannen bakom Bookdown, Yihui Xie, tagit fram något liknande för att kunna blogga genom [Blogdown](https://github.com/rstudio/blogdown). Det är med hjälp av Blogdown som jag har skapat den här bloggen. Jag tänkte först skriva ett blogginlägg där jag beskrev alla steg för att skapa den här bloggen, men det är väl beskrivet i [Blogdowns dokumentation](https://bookdown.org/yihui/blogdown/), så jag tror inte att behovet av ytterligare beskrivningar är så stort. På de flesta punkter har jag följt rekommendationerna i dokumentationen, och jag valde temat [Academic](https://github.com/gcushen/hugo-academic/). En fördel med det temat är, förutom att det är anpassat för personer i akademin, att det har funktionalitet för flera språk. Även om det gick förhållandevis smidigt att sätta upp bloggen har jag gjort lite anpassningar här och var. All kod bakom den här webbsidan går dock att se på [GitHub](https://github.com/richardohrvall/richardohrvall).

Det återstår en del att göra, men förhoppningsvis kommer snart mina gamla bloggposter att ha flyttats över hit. Den gamla webbsidan kommer dock att ligga kvar ett bra tag till. Och jag hoppas att jag får tid skriva en del nya bloggposter i höst.