---
title: Du visste en hel del, John Snow
author: Richard Öhrvall
date: '2017-12-10'
slug: du-visste-en-hel-del-john-snow
categories:
  - metod
tags: []
---

Häromdagen sökte jag en viss uppgift om John Snow, när Googles sökmotor frågade om jag inte egentligen avsåg "Jon Snow". Ett tecken i tiden måhända. Men det är inget ovanligt att en namne ger upphov till missförstånd; att i dag tala om den brasilianske fotbollsspelaren Ronaldo kräver ett förtydligande epitet i stil med den gamle, eller den riktige. Och om man i politikintresserade kretsar vill uttrycka sin beundran för Scott Walker, bör man precisera att man avser mannen med en av pophistoriens vackraste röster och inte den kontroversielle guvenören i Wisconsin. Och det finns onekligen värre öden än att blandas samman med karaktären Jon Snow från Game of Thrones -- han är ändå den rättrådige kungen i norr -- men John Snow var en riktig hjälte.

John Snow brukar benämnas som en av grundarna av epidemiologin, men hans historia innehåller även lärdomar för samhällsvetare. Han var vid 1800-talets mitt läkare i London. Det var då, med en befolkning som uppgick till 2,5 miljoner, världens största stad. Även om London storleksmässigt förvandlats till en modern storstad hade inte infrastrukturen följt med i utvecklingen, framför allt inte vad gäller avlopps- och avfallshantering. Dessutom huserade stadens hus inte bara familjer, utan även hästar, kor och annan boskap. Sammantaget gjorde detta att London bokstavligen stank. Det är därför inte så förvånande att folk trodde att de dödliga kolerautbrotten, som återkommande drabbade London vid den här tiden, hade sin grund i den dåliga luften. John Snow var dock av en annan uppfattning: han var övertygad om att sjukdomen spreds via vatten. 

I dag vet vi att Snow hade rätt, men trots flera utredande skrifter i frågan lyckades han inte övertyga de styrande i staden. När koleran 1854 kraftfullt slog till i en del av Soho, gav sig därför Snow ut för att samla in data. Att utbrottet initialt var begränsat gjorde att han trodde på en bestämd smittopunkt. Han lokaliserade den till vattenpumpen på Broad Street och började därför att samla in uppgifter om antalet dödsfall i de närliggande husen. Till sin hjälp hade han prästen Henry Whitehead: en man väl bekant med folket i kvarteren. Whiteheads insats understryker vikten av att ta hjälp av personer med god lokalkännedom, men tydliggör även att det bakom upptäckter ofta finns avgörande insatser som senare faller i glömska.

Deras datainsamling visade att husen nära pumpen hade betydligt fler dödsfall än hus längre bort. Datamaterialet visade även att ett par närliggande byggnader med ytterst få dödsfall hade eget vatten indraget och därför inte nyttjat pumpen. En av dessa byggnader huserade dessutom ett bryggeri, där arbetarna hade en daglig ranson av öl och därför inte var så intresserade av vatten över huvud taget. Den gedigna statistiken övertygade inte den lokala hälsonämnden helt, men ändå tillräckligt för att de skulle stänga pumpen på Broad Street. Lite senare avtog kolerautbrottet.  

Snow skapade även en karta över Soho för att illustrera dödsfallen till följd av koleran (se figuren oven för ett utsnitt av kartan). På kartan ritade han in pumpen på Broad Street och intill husen markerade han varje dödsfall bland dem som bodde där med ett vertikalt streck. Kartan brukar framhållas som en av tidernas bästa visualiseringar av data. Visserligen övertygade inte kartan alla omedelbart, men den bidrog till att fler och fler över tid insåg att Snow hade rätt i att koleran var vattenburen. Och vid nästa kolerautbrott 1866 utfärdade myndigheterna en uppmaning om att inte dricka vatten som inte först hade kokats, vilket bidrog till att minska antalet dödsfall. Senare byggdes ett mer modernt avloppssystem i London och några fler stora kolerautbrott drabbade inte staden. Lärdomen är att statistik är mer övertygande kraft när den visualiseras.

Vad Snow visade med kartan var ett samband, eller annorlunda uttryckt en korrelation. Men som (väl) ofta brukar framhållas: korrelation är inte kausalitet. Snow gjorde dock ytterligare en studie av 1854 års kolerautbrott; en mer vetenskapligt rigorös studie. Han upptäckte nämligen att några distrikt i London fick sitt vatten från två olika leverantörer: Lambeth och Southwark & Vauxhall. De nyttjade dessutom olika källor: Lambeth hade 1852 börjat ta sitt vatten längre bort från London, medan Southwark & Vauxhall fortsatte ta sitt vatten från ett område dit Themsens smutsiga tidvatten nådde. Snow hade därmed funnit vad vi i dag kallar ett naturligt experiment: vissa hushåll fick ett mer förorenat vatten medan andra fick renare vatten. Även i det avseendet var Snow ett föredöme.

Ett naturligt experiment bygger på att fördelningen mellan experimentgrupp och kontrollgrupp är slumpmässig eller så gott som slumpmässig. I Snows fall innebar det att vilket vattenbolag hushållen valt inte berodde på något som också skulle göra det mer troligt att de drabbades av kolera. Han fann att bolagens vattenledningarna gick längs samma gator och olika husägare gjorde olika val av leverantör, dessutom gjordes dessa val ofta inte av de boende utan av fastighetsägare som bodde på annat håll. När Snow jämförde även de två grupperna och fann att de liknande varandra i flera avseenden, såsom andelen fattiga och rika hushåll. När han däremot jämförde antalet dödsfall var skillnaden otvetydig: bland de hushåll som fick det smutsigare vattnet från Soutwark & Vauxhall var antalet dödsfall 315 per 10 000 personer, bland dem som fick renare vatten från Lambeth var motsvarande siffra blott 37. Då det var så gott som slumpmässigt vilken leverantör hushållen fick sitt vatten från kunde Snow belägga kausalitet: dödsfallen i kolera måste ha orsakats av vattnet.

Broad Street har i dag bytt namn till Broadwick street och pumpen finns inte längre kvar. Men intill där den en gång fanns ligger nu John Snow Pub. Så om du har vägarna förbi kan det vara ett tillfälle att göra ett besök, avnjuta en pint och reflektera över att han visste en del, John Snow.

##Lästips
Steven Johnson (2006) The Ghost Map.
Thad Dunning (2012) Natural Experiments in the Social Sciences (2 ed)

