---
title: Nytt CV i RMarkdown
author: Richard Öhrvall
date: '2017-08-30'
slug: nytt-cv-i-rmarkdown
categories: []
tags:
  - R
  - RMarkdown
---
Jag har nu lyckats flytta alla bloggposter från min gamla Wordpress-blogg, [richardohrvall.com](https://richardohrvall.com/), hit till min nya blogg. Den gamla bloggen får ligga kvar ytterligare en tid, men jag kommer inte att uppdatera den framöver. Det var en del krångel med att flytta över bloggposterna, men den beskrivning som ges i [dokumentationen](https://bookdown.org/yihui/blogdown/) till Blogdown gav viss vägledning.

Från och med nu kommer jag att skriva mina bloggposter i statistikprogrammet R och med hjälp av RMarkdown (se föregående bloggpost för en mer ingående beskrivning). Men min tanke är att försöka gå över till att göra än mer direkt i statistikprogrammet, som exempelvis skapa presentationer och skriva artiklar. Ett sådant steg är att skapa mitt CV direkt i R. Jag hittade en bra [guide](http://svmiller.com/blog/2016/03/svm-r-markdown-cv/) hos Steven V. Miller och ytterligare tips hos [Ryan Peek](https://github.com/ryanpeek/markdown_cv). Utifrån deras mallar har jag skapat en lätt omarbetad version (framför allt för att funka på både svenska och engelska) och med hjälp av den har jag skapat ett CV som kan hittas [här](https://richardohrvall.rbind.io/cv/cv_richard_ohrvall_sv.pdf). Om du vill använda min mall (som baseras på STe) kan du hitta den på min [GitHub](https://github.com/richardohrvall/CV).
