---
title: New blog using R and Blogdown
author: Richard Öhrvall
date: '2018-07-22'
slug: ny-blogg
categories: []
tags:
  - R
  - Blogdown
---

I started blogging in 2010, using a wordpress blog on my website https://richardohrvall.com/. Wordpress is a useful tool for blogging, but I have for different reasons have reached the conclusion that it is time for something new. The primary reason is that I want to integrate my blogging with my data analyses and my other workflow. 

At the same time, I have also started a transition from Stata to R as my main statistical software. One advantage of R is the support for [RMarkdown](http://rmarkdown.rstudio.com/index.html) in RStudio. Using Rmarkdown, you have the flexiblity to convert your document to html, pdf or even Microsoft Word. You can also integrate your R code inside the documents. This facilitates reproducable research and you can easily update your documents when the underlying data is updated.

It is now possible to also blog from R, using RMarkdown and the [Blogdown package](https://github.com/rstudio/blogdown) to R, developed by Yihui Xie. This site is built using Blogdown. I first thought I should write a blogpost on how I created this website, but the documentation of Blogdown is good tutorial on how to do this, so I don't think there is much need for another post on this (there are also already many other valuable post on how to use Blogdown, just Google and you will find them). However, you can find the all the code for this site on my [GitHub](https://github.com/richardohrvall/richardohrvall).

Since Blogdown is based on Hugo, it is possible to select from the many Hugo themes that are available. I opted for the [Academic](https://github.com/gcushen/hugo-academic/) theme, partly because it has some nice features for presenting publications, partly because it seems fairly popular and I hope that this will ensure further development. One feature that has been added as a part of the development of Academic is the opportunity to have a multilingual site. For me, that is a great improvement over my previous Wordpress site. I think that I will mainly blog in Swedish, at least in the nearest future (so do check out the Swedish version of this site if you want to get access to those posts), but hopefully I will also find the time to also blog in English. 